[project]
name = "chess-accuracy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chess>=1.10.0",
    "dearpygui>=1.11.1",
    "numpy>=2.0.2",
    "pyinstaller>=6.10.0",
    "scipy>=1.13.1",
    "tqdm",
]
